### ISSUE TITLE
有Docker镜像吗

### ISSUE THREAD

**Issue by geekidentity** [callmejea/MusicPlayer#1]
使用网页播放本地音乐的大多都是NAS用户（比如我），建议做一个Docker 镜像，给一个配置本地音乐文件的路径。
这样用的人就会多了。

**Comment by jea-tools** [comment]
我过两天搞个吧。有点忙～

**Comment by jea-tools** [comment]
@geekidentity  哦了，有docker了。

**Comment by geekidentity** [comment]
赞，高效

**Comment by geekidentity** [comment]
老哥，你是不是用Mac M1只上传了ARM版的镜像，没有上传X86镜像

**Comment by jea-tools** [comment]
嗯，我只有Mac m1了～要不你build一下～
build命令如下
docker build -t 随便取个名字 .

**Comment by geekidentity** [comment]
歌单读取失败 - 200
![image](https://user-images.githubusercontent.com/23332528/145663849-aba89418-6059-416e-af22-e07f4af45f5c.png)

**Comment by geekidentity** [comment]
http://geekidentity.myqnapcloud.cn:8888/

访问地址

**Comment by jea-tools** [comment]
Warning: file_put_contents(/music/tmp/cache.json): failed to open stream: No such file or directory in /music/api.php on line 18
没有写入权限～
等我找一个x86的机器试试～
12.15我试试吧

**Comment by jea-tools** [comment]
@geekidentity 改好了，原因有两个， 一个是某些版本的docker还不支持utf8字符，我设置了env打了个包，
第二个～打包时候忘记提交tmp目录了。。。导致cache写入失败

现在 docker pull justdoitlikemea/musicplayer:x86 即可，我找了个机器推上了

**Comment by geekidentity** [comment]
可以读取子文件夹吗，列表没有内容

**Comment by jea-tools** [comment]
api.php 第五行，

$files = glob($config['dir'] . '*/*'); 如果层级更深，那么再整一个/*拼后面

**Comment by jea-tools** [comment]
这个是查找文件用的，还可以再加后缀比如：
$files = glob($config['dir'] . '*/*.mp3');只查找mp3文件
